### ISSUE TITLE
Enable C++ Compiling if Network Library is Not Found

### ISSUE THREAD

**Issue by alexanderogle** [simfection/simfection#12]
Currently, C++ optimization is only available if the `network` library is manually compiled and the .so file moved to the /simfection/ directory of the repo. We should add a method which either:

-1) compiles the network library and moves the .so file where it needs to be when simfection is installed with pip
-2) compiles the network library from within the /simfection/ directory when the -cpp flag is added if the network library cannot be found (ModuleImportError exception handling).
-3) add a separate flag to the simfection CLI command which compiles the network library and puts the .so file where it needs to be

I think (2) is probably the ideal solution.

**Comment by gvermillion** [comment]
Option 2 is the best bet. There's no need to add an extra flag to compile what is needed to run `--cpp` when we can add the logic to the `--cpp` flag to compile is necessary.

Also, see my latest comment on [this PR](https://github.com/simfection/simfection/pull/10).

**Comment by alexanderogle** [comment]
This should be implemented now in [PR 10](https://github.com/simfection/simfection/pull/10).

**Comment by gvermillion** [comment]
I'm going to make this as closed, because the docker images compile the C++ code when `python setup.py install` is called.
