### ISSUE TITLE
CPP Versions as Separate Engines

### ISSUE THREAD

**Issue by gvermillion** [simfection/simfection#13]
Rather than have an IF-THEN workflow that handles the `--cpp` flag, we should create separate `ConnectionEngine` and `InteractionEngine` classes that inherit from the non-cpp versions. Then, if we pass `--cpp`, those engines are loaded rather than the pure python ones.

This will also help keep the code much cleaner.

**Comment by gvermillion** [comment]
Plus, this will allows us to test how easy it is to switch out engines AND if they are separate classes, longer branches become less of an issue bc any changes to the initial `ConnectionEngine` won't cause merge conflicts.

This (being separate classes in separate files) is probably the easiest solution.

**Comment by alexanderogle** [comment]
This should be implemented now in [PR 10](https://github.com/simfection/simfection/pull/10).

**Comment by gvermillion** [comment]
Closing.
